In [37]:
import gymnasium as gym
env = gym.make('gym_examples:gym_examples/Reversi-v0', render_mode='text')

In [38]:
import gymnasium as gym
from gymnasium.envs.registration import register

register(
    id="gym_examples/Reversi-v0",
    entry_point="gym_examples.envs:ReversiEnv"
)

env = gym.make('gym_examples/Reversi-v0', render_mode='text')

/opt/anaconda3/envs/pytorch_SKT/lib/python3.9/site-packages/gymnasium/envs/registration.py:694: UserWarning: WARN: Overriding environment gym_examples/Reversi-v0 already in registry.
  logger.warn(f"Overriding environment {new_spec.id} already in registry.")


In [39]:
obs, info = env.reset() 

/opt/anaconda3/envs/pytorch_SKT/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be uint8, actual type: int16
  logger.warn(
/opt/anaconda3/envs/pytorch_SKT/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")


In [40]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . . . . . .
2 | . . . . . . . .
3 | . . . 1 2 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
Gym player: 2, Agent player: 1
<class 'str'>


In [41]:
info['action_mask']

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [42]:
obs, reward, done, _, info = env.step((2,4))

/opt/anaconda3/envs/pytorch_SKT/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be uint8, actual type: int16
  logger.warn(
/opt/anaconda3/envs/pytorch_SKT/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")


In [43]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . . . . . .
2 | . . . . 1 2 . .
3 | . . . 1 2 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
Gym player: 2, Agent player: 1
<class 'str'>


In [44]:
info['action_mask']

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [45]:
obs, reward, done, _,info = env.step((2, 2))

AssertionError: Invalid action (2, 2). Possible moves are [(2, 6), (3, 5), (4, 2), (5, 3)]

In [ ]:
env.render()

Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | . . . . . . . .
1 | . . . . . . . .
2 | . . 1 1 1 2 . .
3 | . . . 1 2 . . .
4 | . . . 2 1 . . .
5 | . . . . . . . .
6 | . . . . . . . .
7 | . . . . . . . .
<class 'str'>


In [ ]:
info['action_mask']

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [ ]:
obs, reward, done,_, info = env.step((0, 2))
env.render()

AssertionError: Invalid action (0, 2). Possible moves are [(2, 6), (3, 5), (4, 2), (5, 3)]

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torchvision.transforms as T

In [ ]:
gamma = 0.99
epsilon = 1.0
epsilon_max = 1.0
epsilon_min = 0.1
epsilon_interval = epsilon_max - epsilon_min
batch_size = 16
max_steps_per_episode = 60
max_episodes = 10000

In [ ]:
env.observation_space

Box(0, 255, (8, 8, 1), uint8)

In [ ]:
num_actions = 64

In [ ]:
class QModel(nn.Module):
  def __init__(self, num_actions):
    super(QModel, self).__init__()
    self.dropout = nn.Dropout(p=0.3)
    self.conv1 = nn.Conv2d(3, 16, kernel_size=3, stride=1, padding='same')
    self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding='same')
    self.conv3 = nn.Conv2d(32, 32, kernel_size=3, stride=1)
    self.flatten = nn.Flatten()
    self.fc1 = nn.Linear(1152, 512)
    self.fc2 = nn.Linear(512, num_actions)

  def forward(self, x):
    x = nn.functional.relu(self.conv1(x))
    x = nn.functional.relu(self.conv2(x))
    x = self.dropout(x)
    x = nn.functional.relu(self.conv3(x))
    x = self.flatten(x)
    x = nn.functional.relu(self.fc1(x))
    x = self.dropout(x)
    return self.fc2(x)

In [ ]:
model = QModel(num_actions)

In [ ]:
model_target = QModel(num_actions)

In [ ]:
loss_function = nn.SmoothL1Loss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.00025)

In [ ]:
action_history = []
action_mask_history = []
state_history = []
state_next_history = []
rewards_history = []
done_history = []

In [ ]:
episode_reward_history = []
running_reward = 0.
episode_count = 0
frame_count = 0

In [ ]:
epsilon_random_frames = 50000
# Number of frames for exploration
epsilon_greedy_frames = 200000.0
# Maximum replay length
# Note: The Deepmind paper suggests 1000000 however this causes memory issues
max_memory_length = 500000
# Train the model after 4 actions
update_after_actions = 4
# How often to update the target network
update_target_network = 10000

In [ ]:
def preprocess_state(obs):
  st = torch.from_numpy(obs).squeeze()
  st = st.to(torch.int64)
  st = torch.nn.functional.one_hot(st, num_classes=3)
  st = st.permute(2, 0, 1)
  return st.to(torch.float32)

In [ ]:
board, info = env.reset()

In [ ]:
st = preprocess_state(board)
st.shape

torch.Size([3, 8, 8])

In [ ]:
def get_greedy_epsilon(model, state, mask):
  global epsilon

  #if frame_count < epsilon_random_frames or np.random.rand(1)[0] < epsilon:
  if np.random.rand(1)[0] < epsilon:
    action = np.random.choice([ i for i in range(num_actions) if mask[i] == 1 ])
  else:
    with torch.no_grad():
      # add a batch axis
      state_tensor = state.unsqueeze(0)
      # compute the q-values
      q_values = model(state_tensor)
      # select the q-values of valid actions
      action = torch.argmax(
        q_values.squeeze() + torch.from_numpy(mask) * 100., dim=0)

  epsilon -= epsilon_interval / epsilon_greedy_frames
  epsilon = max(epsilon, epsilon_min)
  return action

In [ ]:
def get_greedy_action(model, state, mask):
  global epsilon
  with torch.no_grad():
    state_tensor = state.unsqueeze(0) # batch dimension
    q_values = model(state_tensor)
    action = torch.argmax(
      q_values.squeeze() + torch.from_numpy(mask) * 100.,dim=0)
  return action

In [ ]:
def sample_batch(_batch_size):
  indices = np.random.choice(range(len(done_history)), size=_batch_size, replace=False)
  state_sample = np.array([state_history[i].squeeze(0).numpy() for i in indices])
  state_next_sample = np.array([state_next_history[i].squeeze(0).numpy() for i in indices])
  rewards_sample = np.array([rewards_history[i] for i in indices], dtype=np.float32)
  action_sample = np.array([action_history[i] for i in indices])

  # action mask is the mask for the valid actions at the '''next''' state
  action_mask_sample = np.array([action_mask_history[i] for i in indices])
  done_sample = np.array([float(done_history[i]) for i in indices])
  return state_sample, state_next_sample, rewards_sample, action_sample, action_mask_sample, done_sample

In [ ]:
def update_network():
  state_sample, state_next_sample, rewards_sample, action_sample, action_mask_sample, done_sample = \
    sample_batch(batch_size)

  state_sample = torch.tensor(state_sample, dtype=torch.float32)
  state_next_sample = torch.tensor(state_next_sample, dtype=torch.float32)
  action_sample = torch.tensor(action_sample, dtype=torch.int64)
  action_mask_sample = torch.tensor(action_mask_sample, dtype=torch.int64)
  rewards_sample = torch.tensor(rewards_sample, dtype=torch.float32)
  done_sample = torch.tensor(done_sample, dtype=torch.float32)

  with torch.no_grad():
    future_rewards = model_target(state_next_sample)
    max_q_values = torch.max (
        future_rewards + action_mask_sample * 100.,
    dim=1).values.detach() - 100.
    target_q_values = rewards_sample + gamma * max_q_values * (1. - done_sample)

  q_values = model(state_sample)
  q_values_action = q_values.gather(dim=1, index=action_sample.unsqueeze(1)).squeeze(1)
  loss = loss_function(q_values_action, target_q_values)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()


In [ ]:
for _ in range(max_episodes):
  state, info = env.reset()
  state = preprocess_state(state)
  action_mask = info['action_mask'].reshape((-1,))
  episode_reward = 0

  for timestep in range(1, max_steps_per_episode):
    frame_count += 1

    if np.any(action_mask):  # action_mask에 유효한 행동이 있는지 확인
      action = get_greedy_epsilon(model, state, action_mask)
    else:

      break

    state_next, reward, done, _, info = env.step((action // 8, action % 8))
    state_next = preprocess_state(state_next)
    action_mask = info['action_mask'].reshape((-1,))

    episode_reward += reward

    action_history.append(action)
    action_mask_history.append(action_mask)
    state_history.append(state)
    state_next_history.append(state_next)
    rewards_history.append(reward)
    done_history.append(done)

    state = state_next

    if frame_count % update_after_actions == 0 and len(done_history) > batch_size:
      update_network()

    if frame_count % update_target_network == 0:
      model_target.load_state_dict(model.state_dict())

    if len(rewards_history) > max_memory_length:
      del rewards_history[:1]
      del state_history[:1]
      del state_next_history[:1]
      del action_history[:1]
      del action_mask_history[:1]
      del done_history[:1]
    if done:
      break

  episode_count += 1
  episode_reward_history.append(episode_reward)

  if len(episode_reward_history) > 100:
    del episode_reward_history[0]

  running_reward = np.mean(episode_reward_history)

  if episode_count % 10 == 0:
    print(episode_count, frame_count, running_reward)

10 303 32.9
20 607 -8.325
30 881 10.383333333333333
40 1184 -11.1875
50 1485 -9.09
60 1786 -8.566666666666666
70 2089 -5.928571428571429
80 2366 -1.15
90 2672 -4.072222222222222
100 2971 -1.115
110 3273 -4.645
120 3577 -5.925
130 3879 -19.465
140 4182 -16.0
150 4483 -22.35
160 4783 -27.565
170 5085 -31.605
180 5386 -35.92
190 5688 -32.76
200 5990 -33.035
210 6294 -32.435
220 6595 -38.365
230 6901 -28.82
240 7204 -20.465
250 7505 -18.775
260 7807 -18.2
270 8107 -16.985
280 8409 -14.755
290 8710 -17.775
300 9012 -25.25
310 9315 -21.165
320 9615 -8.195
330 9913 -8.39
340 10214 -15.505
350 10515 -4.445
360 10817 -7.95
370 11112 -16.085
380 11416 -9.66
390 11716 -5.94
400 12018 -1.365
410 12320 -5.14
420 12622 -11.84
430 12920 -10.935
440 13220 -5.55
450 13522 -11.32
460 13822 -6.075
470 14124 4.57
480 14427 -2.19
490 14728 -9.785
500 15029 -19.075
510 15332 -22.125
520 15632 -17.89
530 15934 -19.32
540 16237 -21.3
550 16541 -21.305
560 16844 -10.125
570 17143 -16.655
580 17439 -16.27
590 1

In [47]:
import time, sys
from IPython.display import clear_output
board, info = env.reset()
state = preprocess_state(board)
action_mask = info['action_mask'].reshape((-1,))
done = False
env.render()
while not done:
  action = get_greedy_action(model, state, action_mask)
  print("action: ({}, {})".format(action // 8, action % 8))
  sys.stdout.flush()
  time.sleep(1.0)
  clear_output(wait=False)
  board, reward, done, _,info= env.step((action // 8, action % 8))
  state = preprocess_state(board)
  action_mask = info['action_mask'].reshape((-1,))
  env.render()


Current state of the board:
    0 1 2 3 4 5 6 7
-------------------
0 | 1 1 1 1 1 1 1 1
1 | 1 1 1 1 2 1 1 1
2 | 1 1 1 2 1 2 1 1
3 | 1 1 2 2 2 1 1 1
4 | 1 1 1 1 1 1 1 2
5 | 1 1 1 2 2 1 2 2
6 | 1 1 1 1 1 2 2 2
7 | 1 1 1 1 1 1 2 2
Game over! - Winner 1
Gym player: 2, Agent player: 1
<class 'str'>
